version: '3.7'
volumes:
    wordpress_data:
    mysql_data:
services:
  wordpress:
    image: wordpress:latest
    volumes:
            - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
    ports:
      - "7070:80"
    restart: always
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:latest
    volumes:
            - mysql_data:/var/lib/mysql
           # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    # command: ["--init-file", "/docker-entrypoint-initdb.d/init.sql"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
